[package]
name = "showcase"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "showcase"
path = "src/main.rs"

[features]
default = []
hydrate = ["leptos/hydrate"]
ssr = [
    "leptos/ssr",
    "dep:axum",
    "dep:tokio",
    "dep:leptos_axum",
    "dep:tower-http",
    "dep:tracing",
    "dep:tracing-subscriber",
    "ui/ssr",
]

[dependencies]
validator = { workspace = true }
resend-rs = { workspace = true }
http = { workspace = true }
strum = { workspace = true }
reqwest = { workspace = true }
tw_merge = { workspace = true }
icons = { workspace = true }
leptos_ui = { workspace = true }
ui = { workspace = true }

leptos = { workspace = true }
leptos_router = { workspace = true }
leptos_meta = { workspace = true }

console_error_panic_hook = { workspace = true }
serde = { workspace = true }
wasm-bindgen = { workspace = true }
web-sys = { workspace = true }

# ─── SSR-only ───
axum = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
leptos_axum = { workspace = true, optional = true }
tower-http = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }

# ─── Vendor ───
registry = { workspace = true }
app_components = { workspace = true }
app_config = { workspace = true }
app_domain = { workspace = true }
app_routes = { workspace = true }
markdown_crate = { workspace = true }

[package.metadata.leptos]
disable-erase-components = false
name = "showcase"
bin-package = "showcase"
lib-package = "showcase"
site-root = "target/site"
site-pkg-dir = "pkg"
tailwind-input-file = "assets/styles/tailwind.css"
assets-dir = "public"
# site-addr = "0.0.0.0:3854"
site-addr = "127.0.0.1:3854"
reload-port = 3855
browserquery = "defaults"
lib-features = ["hydrate"]
lib-default-features = false
bin-features = ["ssr"]
bin-default-features = false